name: update_smileys_workflow

run-name: 'run #${{ github.run_number }} on ${{ github.event_name }}'

on:
  workflow_dispatch:
  schedule:
    - cron:  '43 14 * * 0'

env:
  THIS_IS_A_TEST_STH: 'TRUE'
  HFR_COOKIES: ${{ secrets.HFR_COOKIES }}
  HFR_COOKIES_TEST: ${{ secrets.HFR_COOKIES_TEST }}

defaults:
  run:
    shell: bash
    working-directory: ./scripts

jobs:
  do_the_shit:
    environment: robot21
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: '0'

      - name: get php 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: php version
        run: php -v

      - name: let's go
        run: ./update_smileys_workflow.php

      - name: git push
        if: ${{ ! ( env.THIS_IS_A_TEST_STH_CACA == 'TRUE' ) }}
        run: |
          git config user.name robot21
          git config user.email robot21@github.com
          #git commit -am 'bot'
          git push
