name: update_smiley_workflow

run-name: "run #${{ github.run_number }} on ${{ github.event_name }}"

on:
  workflow_dispatch:
  schedule:
    - cron:  "43 14 * * 0"

env:
  THIS_IS_A_TEST_STH: "TRUE"
  HFR_COOKIES: ${{ secrets.HFR_COOKIES }}
  HFR_COOKIES_TEST: ${{ secrets.HFR_COOKIES_TEST }}

defaults:
  run:
    shell: bash
    working-directory: ./scripts

jobs:
  do_the_shit:
    environment: robot21
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get php 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: let's go
        run: |
          git checkout main
          ./update_smiley_workflow.php

